version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "4000:80"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:80"
