version: "3.1"
services:
  frontend:
    image: docker.pkg.github.com/domnikl/gridiron/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "4000:80"
  backend:
    image: docker.pkg.github.com/domnikl/gridiron/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4001:80"
    depends_on:
      - db
  db:
    image: library/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: gridiron
      MYSQL_USER: gridiron
      MYSQL_PASSWORD: gridiron
